packages:
  - "apps/*"
  - "docs"
  - "packages/*"
  - "tools/*"

catalog:
  "@actions/core": "^3.0.0"
  "@changesets/cli": "^2.30.0"
  "@cucumber/cucumber": "^12.7.0"
  "@types/node": "^25.6.0"
  "@typescript/native-preview": "7.0.0-dev.20260411.1"
  citty: "^0.2.2"
  lefthook: "^2.1.5"
  oxfmt: "^0.44.0"
  oxlint: "^1.59.0"
  typescript: "^6.0.2"
  vitepress: "^1.6.4"
  vitest: "^4.1.4"
  yaml: "^2.8.3"
