#!/bin/sh

set -eu

AI_PATTERN='Claude|Claude Code|Codex|GitHub Copilot|Copilot|Cursor|Devin|OpenCode|Codeium|Tabnine|Cline|Continue|Aider|Windsurf|Augment|Cody'
BADGE_PATTERN='Generated with|Generated by Copilot|🤖'

usage() {
  cat <<'EOF'
Usage:
  gommage.sh check [range]
  gommage.sh hook <commit-message-file>
EOF
}

check_text() {
  input="$1"

  ai_hits=$(printf '%s\n' "$input" | grep -Ei "Co-authored-by:.*(${AI_PATTERN})" || true)
  badge_hits=$(printf '%s\n' "$input" | grep -Ei "${BADGE_PATTERN}" || true)

  if [ -n "$ai_hits" ] || [ -n "$badge_hits" ]; then
    echo "Gommage found violations:" >&2

    if [ -n "$ai_hits" ]; then
      printf '%s\n' "$ai_hits" | sed 's/^/  x [ai-coauthor] /' >&2
    fi

    if [ -n "$badge_hits" ]; then
      printf '%s\n' "$badge_hits" | sed 's/^/  x [ai-badge] /' >&2
    fi

    echo >&2
    echo "Hint: disable AI co-authorship in your tool or enforce a stricter .gommage.yml through the CLI." >&2
    return 1
  fi
}

run_check() {
  range="${1:-HEAD}"
  commit_count=0

  for sha in $(git rev-list --reverse "$range"); do
    commit_count=$((commit_count + 1))
    message=$(git log -1 --format=%B "$sha")

    if ! check_text "$message"; then
      echo "Commit ${sha} failed authorship policy." >&2
      return 1
    fi
  done

  echo "Gommage checked ${commit_count} commit(s) and found no violations."
}

run_hook() {
  message_file="${1:-}"
  if [ -z "$message_file" ]; then
    echo "gommage.sh hook requires a commit message file." >&2
    exit 1
  fi

  check_text "$(cat "$message_file")"
  echo "Gommage checked 1 commit(s) and found no violations."
}

command="${1:-}"
shift || true

case "$command" in
  check)
    run_check "${1:-HEAD}"
    ;;
  hook)
    run_hook "${1:-}"
    ;;
  help|"")
    usage
    [ -n "$command" ] || exit 1
    ;;
  *)
    echo "Unknown command: $command" >&2
    usage >&2
    exit 1
    ;;
esac
