import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, resolve } from "node:path";

import { parse } from "yaml";

export type ViolationCode =
  | "ai-coauthor"
  | "ai-badge"
  | "blocked-pattern"
  | "blocked-domain"
  | "human-coauthor"
  | "max-authors";

export interface CommitIdentity {
  name: string;
  email: string;
}

export interface CommitInput {
  sha: string;
  message: string;
  authorName: string;
  authorEmail: string;
  committerName?: string;
  committerEmail?: string;
}

/**
 * One or more git revisions or revision ranges. Multiple entries are passed to
 * git as separate arguments, so each may be an independent range such as
 * `origin/main..HEAD`.
 */
export type RevisionSelector = string | string[];

export interface CoAuthor extends CommitIdentity {
  line: string;
}

export interface GommageRules {
  noAiCoauthor: boolean;
  maxAuthors: number | null;
  allowHumanCoauthors: boolean;
  blockedPatterns: string[];
  blockedDomains: string[];
  allowedPatterns: string[];
}

export interface GommageScope {
  range?: RevisionSelector;
}

export interface GommageConfig {
  version: 1;
  rules: GommageRules;
  scope: GommageScope;
}

export interface ConfigLoadResult {
  config: GommageConfig;
  path: string | null;
}

export interface Violation {
  code: ViolationCode;
  message: string;
  line: string;
}

export interface CommitCheckResult {
  commit: CommitInput;
  coAuthors: CoAuthor[];
  violations: Violation[];
}

export interface CheckResult {
  config: GommageConfig;
  commits: CommitCheckResult[];
  violationCount: number;
}

export interface LoadConfigOptions {
  cwd?: string;
  configPath?: string;
}

export interface CheckGitRangeOptions extends LoadConfigOptions {
  range?: RevisionSelector;
}

export interface CheckMessageFileOptions extends LoadConfigOptions {
  messageFile: string;
}

export interface HistoryRewriteOptions extends LoadConfigOptions {
  range?: RevisionSelector;
  replacementAuthorName?: string;
  replacementAuthorEmail?: string;
  /**
   * Sign every rewritten commit. `true` uses the default signing key, a string
   * selects an explicit key id. Requires a usable GPG key in the environment.
   */
  gpgSign?: boolean | string;
}

export interface RewriteCommitPlan {
  sha: string;
  originalAuthorName: string;
  originalAuthorEmail: string;
  sanitizedAuthorName: string;
  sanitizedAuthorEmail: string;
  originalCommitterName: string;
  originalCommitterEmail: string;
  sanitizedCommitterName: string;
  sanitizedCommitterEmail: string;
  originalMessage: string;
  sanitizedMessage: string;
  changes: string[];
}

export interface RewritePlanResult {
  config: GommageConfig;
  range: string;
  ranges: string[];
  commits: RewriteCommitPlan[];
}

const CONFIG_FILE_NAME = ".gommage.yml";

const DEFAULT_CONFIG: GommageConfig = {
  version: 1,
  rules: {
    noAiCoauthor: true,
    maxAuthors: null,
    allowHumanCoauthors: true,
    blockedPatterns: [],
    blockedDomains: [],
    allowedPatterns: [],
  },
  scope: {},
};

const AI_NAME_PATTERNS = [
  /\bclaude(?:\s+code)?\b/i,
  /\bcodex\b/i,
  /\bgithub\s+copilot\b/i,
  /\bcopilot\b/i,
  /\bcursor\b/i,
  /\bdevin\b/i,
  /\bopencode\b/i,
  /\bcodeium\b/i,
  /\btabnine\b/i,
  /\bcline\b/i,
  /\bcontinue\b/i,
  /\baider\b/i,
  /\bwindsurf\b/i,
  /\baugment\b/i,
  /\bcody\b/i,
];

const AI_EMAIL_PATTERNS = [
  /anthropic/i,
  /copilot/i,
  /cursor/i,
  /devin/i,
  /opencode/i,
  /codeium/i,
  /tabnine/i,
  /openai/i,
  /cline/i,
  /continue/i,
  /aider/i,
  /windsurf/i,
  /augment/i,
  /sourcegraph/i,
];

const DEFAULT_BADGE_PATTERNS = [
  /(?:^|\s)🤖\s*generated with\b/i,
  /\bgenerated with \[(?:claude(?:\s+code)?|cursor|codex|github copilot|copilot|devin|opencode|codeium|tabnine|cline|continue|aider|windsurf|augment)\]/i,
  /\bgenerated with (?:claude(?:\s+code)?|cursor|codex|github copilot|copilot|devin|opencode|codeium|tabnine|cline|continue|aider|windsurf|augment)\b/i,
  /\bgenerated by (?:github\s+)?copilot\b/i,
  /\bclaude\.ai\/code\/session[_/]/i,
  /\bclaude\.com\/claude-code\b/i,
];

export function getDefaultConfig(): GommageConfig {
  return structuredClone(DEFAULT_CONFIG);
}

export function loadConfig(options: LoadConfigOptions = {}): ConfigLoadResult {
  const cwd = resolve(options.cwd ?? process.cwd());
  const configPath = options.configPath ? resolve(cwd, options.configPath) : findConfigPath(cwd);

  if (!configPath) {
    return {
      config: getDefaultConfig(),
      path: null,
    };
  }

  const raw = readFileSync(configPath, "utf8");
  const parsed = parse(raw) as Record<string, unknown> | null;

  return {
    config: mergeConfig(parsed),
    path: configPath,
  };
}

export function checkCommitMessage(
  commit: CommitInput,
  config: GommageConfig = getDefaultConfig(),
): CommitCheckResult {
  const coAuthors = extractCoAuthors(commit.message);
  const allowMatchers = config.rules.allowedPatterns.map(toPattern);
  const violations: Violation[] = [];

  for (const coAuthor of coAuthors) {
    if (config.rules.noAiCoauthor && isAiIdentity(coAuthor)) {
      pushViolation(violations, allowMatchers, {
        code: "ai-coauthor",
        message: `AI co-authorship detected: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }

    if (!config.rules.allowHumanCoauthors && !isAiIdentity(coAuthor)) {
      pushViolation(violations, allowMatchers, {
        code: "human-coauthor",
        message: `Human co-author not allowed by policy: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }

    if (matchesBlockedDomain(coAuthor.email, config.rules.blockedDomains)) {
      pushViolation(violations, allowMatchers, {
        code: "blocked-domain",
        message: `Blocked email domain detected: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }
  }

  if (matchesBlockedDomain(commit.authorEmail, config.rules.blockedDomains)) {
    const line = `Author: ${commit.authorName} <${commit.authorEmail}>`;
    pushViolation(violations, allowMatchers, {
      code: "blocked-domain",
      message: `Blocked email domain detected: "${line}"`,
      line,
    });
  }

  const lines = splitMessageLines(commit.message);

  for (const line of lines) {
    const { violation } = classifyFreeTextLine(line, config, allowMatchers);

    if (violation) {
      pushViolation(violations, allowMatchers, violation);
    }
  }

  const maxAuthors = config.rules.maxAuthors;
  if (maxAuthors !== null) {
    const authorCount = 1 + coAuthors.length;
    if (authorCount > maxAuthors) {
      const line = `authors=${authorCount} max=${maxAuthors}`;
      pushViolation(violations, allowMatchers, {
        code: "max-authors",
        message: `Commit exceeds max authors policy (${authorCount}/${maxAuthors}).`,
        line,
      });
    }
  }

  return {
    commit,
    coAuthors,
    violations: dedupeViolations(violations),
  };
}

export function checkCommits(
  commits: CommitInput[],
  config: GommageConfig = getDefaultConfig(),
): CheckResult {
  const results = commits.map((commit) => checkCommitMessage(commit, config));

  return {
    config,
    commits: results,
    violationCount: results.reduce((count, result) => count + result.violations.length, 0),
  };
}

export function checkGitRange(options: CheckGitRangeOptions = {}): CheckResult {
  const { config } = loadConfig(options);
  const ranges = normalizeRanges(options.range ?? config.scope.range);
  const commits = readCommitsFromGit({
    cwd: options.cwd,
    range: ranges.length > 0 ? ranges : "HEAD",
  });

  return checkCommits(commits, config);
}

export function checkMessageFile(options: CheckMessageFileOptions): CheckResult {
  const { config } = loadConfig(options);
  const message = readFileSync(resolve(options.cwd ?? process.cwd(), options.messageFile), "utf8");
  const commit: CommitInput = {
    sha: "COMMIT_MSG",
    message,
    authorName: "",
    authorEmail: "",
  };

  return checkCommits([commit], config);
}

export function planHistoryRewrite(options: HistoryRewriteOptions = {}): RewritePlanResult {
  const cwd = resolve(options.cwd ?? process.cwd());
  const { config } = loadConfig({ cwd, configPath: options.configPath });
  const ranges = normalizeRanges(options.range ?? config.scope.range);
  const effectiveRanges = ranges.length > 0 ? ranges : ["--all"];
  const commits = readCommitsFromGit({ cwd, range: effectiveRanges });
  const replacementIdentity = getRewriteReplacementIdentity(cwd, options);

  if (replacementIdentity) {
    assertUsableReplacementIdentity(replacementIdentity, config);
  }

  return {
    config,
    range: effectiveRanges.join(" "),
    ranges: effectiveRanges,
    commits: commits
      .map((commit) => planCommitRewrite(commit, config, replacementIdentity))
      .filter((commit): commit is RewriteCommitPlan => commit !== null),
  };
}

export function rewriteGitHistory(options: HistoryRewriteOptions = {}): RewritePlanResult {
  const cwd = resolve(options.cwd ?? process.cwd());
  const plan = planHistoryRewrite({ ...options, cwd });

  if (plan.commits.length === 0) {
    return plan;
  }

  const tempDir = mkdtempSync(resolve(tmpdir(), "gommage-rewrite-"));
  const planFile = resolve(tempDir, "plan.json");
  const helperFile = resolve(tempDir, "rewrite-helper.cjs");

  writeFileSync(
    planFile,
    JSON.stringify(
      plan.commits.map((commit) => ({
        sha: commit.sha,
        sanitizedAuthorName: commit.sanitizedAuthorName,
        sanitizedAuthorEmail: commit.sanitizedAuthorEmail,
        sanitizedCommitterName: commit.sanitizedCommitterName,
        sanitizedCommitterEmail: commit.sanitizedCommitterEmail,
        sanitizedMessage: commit.sanitizedMessage,
      })),
    ),
  );
  writeFileSync(helperFile, getRewriteHelperScript());

  const envFilter = `eval "$(${quoteForShell(process.execPath)} ${quoteForShell(helperFile)} ${quoteForShell(planFile)} env "$GIT_COMMIT")"`;
  const msgFilter = [
    quoteForShell(process.execPath),
    quoteForShell(helperFile),
    quoteForShell(planFile),
    "msg",
    '"$GIT_COMMIT"',
  ].join(" ");

  const filterArgs = ["filter-branch", "-f", "--env-filter", envFilter, "--msg-filter", msgFilter];

  const signing = normalizeGpgSign(options.gpgSign);
  if (signing) {
    filterArgs.push("--commit-filter", buildCommitFilter(signing));
  }

  filterArgs.push("--tag-name-filter", "cat", "--", ...plan.ranges);

  try {
    execFileSync("git", filterArgs, {
      cwd,
      stdio: "ignore",
      env: {
        ...process.env,
        FILTER_BRANCH_SQUELCH_WARNING: "1",
      },
    });
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }

  return plan;
}

export function formatRewritePlan(
  plan: RewritePlanResult,
  options: { dryRun?: boolean } = {},
): string {
  const dryRun = options.dryRun ?? false;

  if (plan.commits.length === 0) {
    return dryRun
      ? "Gommage found no commits that would need rewriting."
      : "Gommage found no commits that needed rewriting.";
  }

  const heading = dryRun
    ? `Gommage would rewrite ${plan.commits.length} commit(s).`
    : `Gommage rewrote ${plan.commits.length} commit(s).`;
  const details = plan.commits.map((commit) => {
    const subject = firstNonEmptyLine(commit.sanitizedMessage) ?? "(no subject)";

    if (!dryRun) {
      const lines = [`- ${commit.sha.slice(0, 7)} ${subject}`];

      for (const change of commit.changes) {
        lines.push(`  - ${change}`);
      }

      if (
        commit.originalAuthorName !== commit.sanitizedAuthorName ||
        commit.originalAuthorEmail !== commit.sanitizedAuthorEmail
      ) {
        lines.push(
          `  - author: ${commit.originalAuthorName} <${commit.originalAuthorEmail}> -> ${commit.sanitizedAuthorName} <${commit.sanitizedAuthorEmail}>`,
        );
      }

      if (
        commit.originalCommitterName !== commit.sanitizedCommitterName ||
        commit.originalCommitterEmail !== commit.sanitizedCommitterEmail
      ) {
        lines.push(
          `  - committer: ${commit.originalCommitterName} <${commit.originalCommitterEmail}> -> ${commit.sanitizedCommitterName} <${commit.sanitizedCommitterEmail}>`,
        );
      }

      return lines.join("\n");
    }

    return [
      `Commit ${commit.sha.slice(0, 7)} preview`,
      "Old author:",
      `  ${commit.originalAuthorName} <${commit.originalAuthorEmail}>`,
      "New author:",
      `  ${commit.sanitizedAuthorName} <${commit.sanitizedAuthorEmail}>`,
      "Old committer:",
      `  ${commit.originalCommitterName} <${commit.originalCommitterEmail}>`,
      "New committer:",
      `  ${commit.sanitizedCommitterName} <${commit.sanitizedCommitterEmail}>`,
      "Old message:",
      indentBlock(commit.originalMessage),
      "New message:",
      indentBlock(commit.sanitizedMessage),
      "Planned changes:",
      ...commit.changes.map((change) => `  - ${change}`),
    ].join("\n");
  });

  const lines = [heading, `Range: ${plan.range}`, "", ...details];

  if (dryRun) {
    lines.push("", "No git history was changed because --dry-run was set.");
  } else {
    lines.push("", "Git backup refs were written under refs/original/ by git filter-branch.");
  }

  return lines.join("\n");
}

export function readCommitsFromGit(options: {
  cwd?: string;
  range: RevisionSelector;
}): CommitInput[] {
  const cwd = resolve(options.cwd ?? process.cwd());
  const ranges = normalizeRanges(options.range);
  const output = execFileSync(
    "git",
    [
      "log",
      "--format=%H%x00%an%x00%ae%x00%cn%x00%ce%x00%B%x00%x1e",
      ...(ranges.length > 0 ? ranges : ["HEAD"]),
    ],
    {
      cwd,
      encoding: "utf8",
    },
  );

  return output
    .split("\x1e")
    .map((chunk: string) => chunk.trim())
    .filter(Boolean)
    .map((chunk: string) => {
      const [sha, authorName, authorEmail, committerName, committerEmail, message] =
        chunk.split("\x00");

      return {
        sha: sha ?? "",
        authorName: authorName ?? "",
        authorEmail: authorEmail ?? "",
        committerName: committerName ?? "",
        committerEmail: committerEmail ?? "",
        message: (message ?? "").trimEnd(),
      };
    });
}

export function formatCheckResult(result: CheckResult): string {
  if (result.violationCount === 0) {
    if (result.commits.length === 0) {
      return "Gommage checked 0 commits and found no violations.";
    }

    return `Gommage checked ${result.commits.length} commit(s) and found no violations.`;
  }

  const blocks = result.commits
    .filter((commit) => commit.violations.length > 0)
    .map((commit) => {
      const commitLabel =
        commit.commit.sha === "COMMIT_MSG"
          ? "commit message"
          : `commit ${commit.commit.sha.slice(0, 7)}`;
      const header = `Gommage found ${commit.violations.length} violation(s) in ${commitLabel}:`;
      const lines = commit.violations.map(
        (violation) => `  x [${violation.code}] ${violation.message}`,
      );

      return [header, "", ...lines].join("\n");
    });

  blocks.push(
    "",
    "Hint: Configure your AI tool to disable co-authorship, or update .gommage.yml to allow it.",
  );

  return blocks.join("\n");
}

export function hasViolations(result: { violationCount: number }): boolean {
  return result.violationCount > 0;
}

export type PullRequestSurface = "title" | "body";

export interface PullRequestTarget {
  baseRefName: string;
  headRefName: string;
}

export interface PullRequestInput extends Partial<PullRequestTarget> {
  number: number;
  url: string;
  title: string;
  body: string;
}

/**
 * The revision range a pull request contributes to its base branch. Both sides
 * are qualified with `origin/` so a stale local base cannot widen the range.
 */
export function pullRequestRevisionRange(target: PullRequestTarget): string {
  return `origin/${target.baseRefName}..${target.headRefName}`;
}

export interface PullRequestSurfaceResult {
  surface: PullRequestSurface;
  original: string;
  sanitized: string;
  violations: Violation[];
  changes: string[];
}

export interface PullRequestCheckResult {
  config: GommageConfig;
  pullRequest: PullRequestInput;
  surfaces: PullRequestSurfaceResult[];
  violationCount: number;
}

export interface PullRequestRewritePlan {
  config: GommageConfig;
  pullRequest: PullRequestInput;
  surfaces: PullRequestSurfaceResult[];
}

/**
 * Scans free text, such as a pull request title or body, for AI attribution
 * lines. Unlike commit messages this preserves the original line content, so
 * markdown indentation survives, and every flagged line is reported with the
 * replacement text that would remove it.
 */
export function scanSurface(
  surface: PullRequestSurface,
  text: string,
  config: GommageConfig = getDefaultConfig(),
): PullRequestSurfaceResult {
  const allowMatchers = config.rules.allowedPatterns.map(toPattern);
  const violations: Violation[] = [];
  const changes: string[] = [];
  const keptLines: string[] = [];

  for (const rawLine of text.split(/\r?\n/u)) {
    if (!rawLine.trim()) {
      keptLines.push("");
      continue;
    }

    const trimmed = rawLine.trim();
    const coAuthor = parseCoAuthorLine(trimmed);

    if (coAuthor && config.rules.noAiCoauthor && isAiIdentity(coAuthor)) {
      violations.push({
        code: "ai-coauthor",
        message: `AI co-authorship detected: "${trimmed}"`,
        line: trimmed,
      });
      changes.push(`remove AI co-author trailer: "${trimmed}"`);
      continue;
    }

    const classification = classifyFreeTextLine(trimmed, config, allowMatchers);

    if (classification.violation) {
      violations.push(classification.violation);
      if (classification.change) {
        changes.push(classification.change);
      }
      continue;
    }

    keptLines.push(rawLine);
  }

  return {
    surface,
    original: text,
    violations: dedupeViolations(violations),
    sanitized: normalizeCommitMessage(keptLines),
    changes,
  };
}

export function checkPullRequest(
  pullRequest: PullRequestInput,
  config: GommageConfig = getDefaultConfig(),
): PullRequestCheckResult {
  const surfaces = [
    scanSurface("title", pullRequest.title, config),
    scanSurface("body", pullRequest.body, config),
  ];

  return {
    config,
    pullRequest,
    surfaces,
    violationCount: surfaces.reduce((count, surface) => count + surface.violations.length, 0),
  };
}

export function planPullRequestRewrite(
  pullRequest: PullRequestInput,
  config: GommageConfig = getDefaultConfig(),
): PullRequestRewritePlan {
  const check = checkPullRequest(pullRequest, config);

  return {
    config,
    pullRequest,
    surfaces: check.surfaces.filter((surface) => surface.changes.length > 0),
  };
}

export function formatPullRequestCheck(result: PullRequestCheckResult): string {
  const label = `pull request #${result.pullRequest.number}`;

  if (result.violationCount === 0) {
    return `Gommage checked the ${label} title and body and found no violations.`;
  }

  const blocks = result.surfaces
    .filter((surface) => surface.violations.length > 0)
    .map((surface) => {
      const header = `Gommage found ${surface.violations.length} violation(s) in the ${label} ${surface.surface}:`;
      const lines = surface.violations.map(
        (violation) => `  x [${violation.code}] ${violation.message}`,
      );

      return [header, "", ...lines].join("\n");
    });

  return [
    ...blocks,
    "",
    `Hint: run "gommage pr fix" to strip the flagged lines from ${label}.`,
  ].join("\n");
}

export function formatPullRequestPlan(
  plan: PullRequestRewritePlan,
  options: { dryRun?: boolean } = {},
): string {
  const dryRun = options.dryRun ?? false;
  const label = `pull request #${plan.pullRequest.number}`;

  if (plan.surfaces.length === 0) {
    return `Gommage found no AI attribution in the ${label} title or body.`;
  }

  const fields = plan.surfaces.map((surface) => surface.surface).join(" and ");
  const heading = dryRun
    ? `Gommage would rewrite the ${label} ${fields}.`
    : `Gommage rewrote the ${label} ${fields}.`;

  const details = plan.surfaces.map((surface) => {
    const lines = [
      `${surface.surface} preview`,
      "Old:",
      indentBlock(surface.original),
      "New:",
      indentBlock(surface.sanitized),
      "Planned changes:",
      ...surface.changes.map((change) => `  - ${change}`),
    ];

    return lines.join("\n");
  });

  const lines = [heading, "", ...details];

  if (dryRun) {
    lines.push("", "No pull request was changed because --dry-run was set.");
  }

  return lines.join("\n");
}

function findConfigPath(startDir: string): string | null {
  let current = startDir;

  while (true) {
    const candidate = resolve(current, CONFIG_FILE_NAME);
    if (existsSync(candidate)) {
      return candidate;
    }

    const parent = dirname(current);
    if (parent === current) {
      return null;
    }

    current = parent;
  }
}

function planCommitRewrite(
  commit: CommitInput,
  config: GommageConfig,
  replacementIdentity: CommitIdentity | null,
): RewriteCommitPlan | null {
  const allowMatchers = config.rules.allowedPatterns.map(toPattern);
  const lineEntries = commit.message.split(/\r?\n/u).map((line) => ({
    line: line.replace(/[ \t]+$/u, ""),
    trimmed: line.trim(),
    keep: true,
    coAuthor: null as CoAuthor | null,
  }));
  const changes: string[] = [];
  const keptCoAuthorIndexes: number[] = [];

  for (const [index, entry] of lineEntries.entries()) {
    if (!entry.trimmed) {
      continue;
    }

    const coAuthor = parseCoAuthorLine(entry.trimmed);
    if (coAuthor) {
      entry.coAuthor = coAuthor;

      if (allowMatchers.some((matcher) => matcher.test(entry.trimmed))) {
        keptCoAuthorIndexes.push(index);
        continue;
      }

      if (config.rules.noAiCoauthor && isAiIdentity(coAuthor)) {
        entry.keep = false;
        changes.push(`remove AI co-author trailer: "${entry.trimmed}"`);
        continue;
      }

      if (!config.rules.allowHumanCoauthors) {
        entry.keep = false;
        changes.push(`remove disallowed co-author trailer: "${entry.trimmed}"`);
        continue;
      }

      if (matchesBlockedDomain(coAuthor.email, config.rules.blockedDomains)) {
        entry.keep = false;
        changes.push(`remove blocked-domain co-author trailer: "${entry.trimmed}"`);
        continue;
      }

      keptCoAuthorIndexes.push(index);
      continue;
    }

    if (allowMatchers.some((matcher) => matcher.test(entry.trimmed))) {
      continue;
    }

    if (DEFAULT_BADGE_PATTERNS.some((pattern) => pattern.test(entry.trimmed))) {
      entry.keep = false;
      changes.push(`remove AI badge line: "${entry.trimmed}"`);
      continue;
    }

    for (const blockedPattern of config.rules.blockedPatterns) {
      if (toPattern(blockedPattern).test(entry.trimmed)) {
        entry.keep = false;
        changes.push(`remove blocked pattern line: "${entry.trimmed}"`);
        break;
      }
    }
  }

  if (config.rules.maxAuthors !== null) {
    const maxCoAuthors = Math.max(config.rules.maxAuthors - 1, 0);
    const extraCoAuthorIndexes = keptCoAuthorIndexes.slice(maxCoAuthors);

    for (const index of extraCoAuthorIndexes) {
      if (lineEntries[index]) {
        lineEntries[index].keep = false;
        changes.push(`remove extra co-author trailer: "${lineEntries[index].trimmed}"`);
      }
    }
  }

  let sanitizedAuthorName = commit.authorName;
  let sanitizedAuthorEmail = commit.authorEmail;

  if (shouldRewriteAuthor(commit, config)) {
    if (!replacementIdentity) {
      throw new Error(
        `Commit ${commit.sha.slice(0, 7)} requires author replacement. Set git user.name/user.email in the target repository or pass --author-name and --author-email.`,
      );
    }

    sanitizedAuthorName = replacementIdentity.name;
    sanitizedAuthorEmail = replacementIdentity.email;
    changes.push("replace author identity");
  }

  // A rewritten commit is committed by whoever runs the rewrite, matching what
  // `git rebase` and `git commit --amend` do. Without a replacement identity the
  // original committer is preserved rather than replaced by the author.
  const originalCommitterName = commit.committerName ?? commit.authorName;
  const originalCommitterEmail = commit.committerEmail ?? commit.authorEmail;
  const sanitizedCommitterName = replacementIdentity?.name ?? originalCommitterName;
  const sanitizedCommitterEmail = replacementIdentity?.email ?? originalCommitterEmail;

  if (
    sanitizedCommitterName !== originalCommitterName ||
    sanitizedCommitterEmail !== originalCommitterEmail
  ) {
    changes.push("replace committer identity");
  }

  removeSingleAuthorTrailers(
    lineEntries,
    keptCoAuthorIndexes,
    {
      name: sanitizedAuthorName,
      email: sanitizedAuthorEmail,
    },
    changes,
  );

  const sanitizedMessage = normalizeCommitMessage(
    lineEntries.filter((entry) => entry.keep).map((entry) => entry.line),
  );

  if (!sanitizedMessage) {
    throw new Error(
      `Unable to automatically sanitize commit ${commit.sha.slice(0, 7)} because the rewritten message would be empty.`,
    );
  }

  if (
    sanitizedMessage === commit.message &&
    sanitizedAuthorName === commit.authorName &&
    sanitizedAuthorEmail === commit.authorEmail &&
    sanitizedCommitterName === originalCommitterName &&
    sanitizedCommitterEmail === originalCommitterEmail
  ) {
    return null;
  }

  return {
    sha: commit.sha,
    originalAuthorName: commit.authorName,
    originalAuthorEmail: commit.authorEmail,
    sanitizedAuthorName,
    sanitizedAuthorEmail,
    originalCommitterName,
    originalCommitterEmail,
    sanitizedCommitterName,
    sanitizedCommitterEmail,
    originalMessage: commit.message,
    sanitizedMessage,
    changes,
  };
}

function mergeConfig(parsed: Record<string, unknown> | null): GommageConfig {
  if (!parsed) {
    return getDefaultConfig();
  }

  const version = parsed.version;
  if (version !== undefined && version !== 1) {
    throw new Error(`Unsupported .gommage.yml version: ${String(version)}`);
  }

  const rules = asObject(parsed.rules);
  const scope = asObject(parsed.scope);
  const defaults = getDefaultConfig();

  return {
    version: 1,
    rules: {
      noAiCoauthor: asBoolean(rules["no-ai-coauthor"], defaults.rules.noAiCoauthor),
      maxAuthors: asNullableNumber(rules["max-authors"], defaults.rules.maxAuthors),
      allowHumanCoauthors: asBoolean(
        rules["allow-human-coauthors"],
        defaults.rules.allowHumanCoauthors,
      ),
      blockedPatterns: asStringArray(rules["blocked-patterns"], defaults.rules.blockedPatterns),
      blockedDomains: asStringArray(rules["blocked-domains"], defaults.rules.blockedDomains),
      allowedPatterns: asStringArray(rules["allowed-patterns"], defaults.rules.allowedPatterns),
    },
    scope: {
      range: asRevisionSelector(scope.range),
    },
  };
}

function extractCoAuthors(message: string): CoAuthor[] {
  return splitMessageLines(message)
    .map((line) => parseCoAuthorLine(line))
    .filter((value): value is CoAuthor => value !== null);
}

function isAiIdentity(identity: CommitIdentity): boolean {
  return (
    AI_NAME_PATTERNS.some((pattern) => pattern.test(identity.name)) ||
    AI_EMAIL_PATTERNS.some((pattern) => pattern.test(identity.email))
  );
}

function shouldRewriteAuthor(commit: CommitInput, config: GommageConfig): boolean {
  return (
    isAiIdentity({ name: commit.authorName, email: commit.authorEmail }) ||
    matchesBlockedDomain(commit.authorEmail, config.rules.blockedDomains)
  );
}

function matchesBlockedDomain(email: string, blockedDomains: string[]): boolean {
  if (!email) {
    return false;
  }

  const normalizedEmail = email.toLowerCase();
  const atIndex = normalizedEmail.lastIndexOf("@");
  const domain = atIndex === -1 ? normalizedEmail : normalizedEmail.slice(atIndex + 1);

  return blockedDomains.some((entry) => {
    const normalizedEntry = entry.toLowerCase();
    if (!normalizedEntry) {
      return false;
    }

    if (normalizedEntry.includes("@")) {
      return normalizedEmail === normalizedEntry;
    }

    return domain === normalizedEntry || domain.endsWith(`.${normalizedEntry}`);
  });
}

function pushViolation(
  violations: Violation[],
  allowMatchers: RegExp[],
  violation: Violation,
): void {
  if (allowMatchers.some((matcher) => matcher.test(violation.line))) {
    return;
  }

  violations.push(violation);
}

function dedupeViolations(violations: Violation[]): Violation[] {
  const seen = new Set<string>();

  return violations.filter((violation) => {
    const key = `${violation.code}:${violation.line}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

interface LineClassification {
  violation: Violation | null;
  change: string | null;
}

/**
 * The single rule engine behind commit messages and pull request text. A line
 * that matches an allowed pattern is never reported, badge patterns win over
 * configured blocked patterns, and only the first match is reported so one line
 * never produces duplicate violations.
 */
function classifyFreeTextLine(
  line: string,
  config: GommageConfig,
  allowMatchers: RegExp[],
): LineClassification {
  if (allowMatchers.some((matcher) => matcher.test(line))) {
    return { violation: null, change: null };
  }

  for (const pattern of DEFAULT_BADGE_PATTERNS) {
    if (pattern.test(line)) {
      return {
        violation: {
          code: "ai-badge",
          message: `AI generation badge found: "${line}"`,
          line,
        },
        change: `remove AI badge line: "${line}"`,
      };
    }
  }

  for (const entry of config.rules.blockedPatterns) {
    if (toPattern(entry).test(line)) {
      return {
        violation: {
          code: "blocked-pattern",
          message: `Blocked pattern matched: "${line}"`,
          line,
        },
        change: `remove blocked pattern line: "${line}"`,
      };
    }
  }

  return { violation: null, change: null };
}

function toPattern(value: string): RegExp {
  const raw = value.trim();
  const regexMatch = /^\/(.+)\/([dgimsuvy]*)$/.exec(raw);
  if (regexMatch) {
    return new RegExp(regexMatch[1], regexMatch[2]);
  }

  return new RegExp(escapeRegExp(raw), "i");
}

function splitMessageLines(message: string): string[] {
  return message
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter(Boolean);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function parseCoAuthorLine(line: string): CoAuthor | null {
  const match = /^Co-authored-by:\s*(.+?)\s*<([^>]+)>\s*$/i.exec(line);
  if (!match) {
    return null;
  }

  return {
    line,
    name: match[1].trim(),
    email: match[2].trim(),
  };
}

function normalizeCommitMessage(lines: string[]): string {
  const normalized: string[] = [];

  for (const line of lines) {
    if (!line.trim()) {
      if (normalized.length === 0 || !normalized[normalized.length - 1]?.trim()) {
        continue;
      }

      normalized.push("");
      continue;
    }

    normalized.push(line);
  }

  while (normalized.length > 0 && !normalized[normalized.length - 1]?.trim()) {
    normalized.pop();
  }

  return normalized.join("\n");
}

function firstNonEmptyLine(message: string): string | null {
  for (const line of message.split(/\r?\n/u)) {
    const trimmed = line.trim();
    if (trimmed) {
      return trimmed;
    }
  }

  return null;
}

function removeSingleAuthorTrailers(
  lineEntries: Array<{ line: string; trimmed: string; keep: boolean; coAuthor: CoAuthor | null }>,
  keptCoAuthorIndexes: number[],
  author: CommitIdentity,
  changes: string[],
): void {
  const remainingCoAuthors = keptCoAuthorIndexes
    .map((index) => lineEntries[index])
    .filter(
      (entry): entry is { line: string; trimmed: string; keep: boolean; coAuthor: CoAuthor } =>
        Boolean(entry?.keep && entry.coAuthor),
    )
    .map((entry) => entry.coAuthor);

  const uniqueAuthors = [author, ...remainingCoAuthors].reduce<CommitIdentity[]>((all, current) => {
    if (all.some((known) => sameIdentity(known, current))) {
      return all;
    }

    all.push(current);
    return all;
  }, []);

  if (uniqueAuthors.length > 1) {
    return;
  }

  for (const index of keptCoAuthorIndexes) {
    const entry = lineEntries[index];
    if (!entry?.keep || !entry.coAuthor) {
      continue;
    }

    entry.keep = false;
    changes.push(`remove redundant co-author trailer: "${entry.trimmed}"`);
  }
}

function indentBlock(value: string): string {
  return value
    .split(/\r?\n/u)
    .map((line) => `  ${line}`)
    .join("\n");
}

function getRewriteReplacementIdentity(
  cwd: string,
  options: HistoryRewriteOptions,
): CommitIdentity | null {
  const name = options.replacementAuthorName ?? readGitConfigValue(cwd, "user.name");
  const email = options.replacementAuthorEmail ?? readGitConfigValue(cwd, "user.email");

  if (!name || !email) {
    return null;
  }

  return { name, email };
}

function sameIdentity(left: CommitIdentity, right: CommitIdentity): boolean {
  const leftName = left.name.trim().toLowerCase();
  const rightName = right.name.trim().toLowerCase();
  const leftEmail = left.email.trim().toLowerCase();
  const rightEmail = right.email.trim().toLowerCase();

  return Boolean((leftEmail && leftEmail === rightEmail) || (leftName && leftName === rightName));
}

function readGitConfigValue(cwd: string, key: string): string | null {
  try {
    return execFileSync("git", ["config", "--get", key], {
      cwd,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

function quoteForShell(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function getRewriteHelperScript(): string {
  return [
    "const fs = require('node:fs');",
    "const plan = new Map(JSON.parse(fs.readFileSync(process.argv[2], 'utf8')).map((entry) => [entry.sha, entry]));",
    "const mode = process.argv[3];",
    "const sha = process.argv[4];",
    "const entry = plan.get(sha);",
    "if (!entry) {",
    "  if (mode === 'msg') {",
    "    process.stdin.pipe(process.stdout);",
    "    process.stdin.resume();",
    "  } else {",
    "    process.exit(0);",
    "  }",
    "} else if (mode === 'msg') {",
    "  process.stdout.write(`${entry.sanitizedMessage}\\n`);",
    "  process.exit(0);",
    "} else if (mode === 'env') {",
    "  const quote = (value) => `'${String(value).replace(/'/g, `'\\\\''`)}'`;",
    "  process.stdout.write([",
    "    `export GIT_AUTHOR_NAME=${quote(entry.sanitizedAuthorName)}`,",
    "    `export GIT_AUTHOR_EMAIL=${quote(entry.sanitizedAuthorEmail)}`,",
    "    `export GIT_COMMITTER_NAME=${quote(entry.sanitizedCommitterName)}`,",
    "    `export GIT_COMMITTER_EMAIL=${quote(entry.sanitizedCommitterEmail)}`",
    "  ].join('\\n'));",
    "}",
  ].join("\n");
}

function asObject(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  return value as Record<string, unknown>;
}

function asBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === "boolean" ? value : fallback;
}

function asNullableNumber(value: unknown, fallback: number | null): number | null {
  if (value === null) {
    return null;
  }

  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function asStringArray(value: unknown, fallback: string[]): string[] {
  if (!Array.isArray(value)) {
    return [...fallback];
  }

  return value.filter((entry): entry is string => typeof entry === "string");
}

/**
 * Accepts a single revision string or a list of them, dropping empty entries so
 * a blank config value falls back to the caller's default.
 */
function asRevisionSelector(value: unknown): RevisionSelector | undefined {
  if (typeof value === "string") {
    return value.length > 0 ? value : undefined;
  }

  if (!Array.isArray(value)) {
    return undefined;
  }

  const ranges = value.filter(
    (entry): entry is string => typeof entry === "string" && entry.length > 0,
  );

  return ranges.length > 0 ? ranges : undefined;
}

/** Normalizes any revision selector into the argument list git receives. */
export function normalizeRanges(value: RevisionSelector | undefined | null): string[] {
  if (value === undefined || value === null) {
    return [];
  }

  const entries = Array.isArray(value) ? value : [value];

  return entries.map((entry) => entry.trim()).filter(Boolean);
}

function normalizeGpgSign(value: boolean | string | undefined): true | string | null {
  if (value === undefined || value === false) {
    return null;
  }

  if (value === true) {
    return true;
  }

  const keyId = value.trim();
  return keyId.length > 0 ? keyId : true;
}

function buildCommitFilter(signing: true | string): string {
  const keyArgument = signing === true ? "-S" : `-S${quoteForShell(signing)}`;
  return `git commit-tree ${keyArgument} "$@"`;
}

function assertUsableReplacementIdentity(identity: CommitIdentity, config: GommageConfig): void {
  if (
    !isAiIdentity(identity) &&
    !matchesBlockedDomain(identity.email, config.rules.blockedDomains)
  ) {
    return;
  }

  throw new Error(
    `Refusing to rewrite history: the replacement identity "${identity.name} <${identity.email}>" is itself an AI identity or a blocked domain, so commits would not actually be cleaned up. Set git user.name/user.email to the human identity, or pass --author-name and --author-email.`,
  );
}
