import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { parse } from "yaml";

export type ViolationCode =
  | "ai-coauthor"
  | "ai-badge"
  | "blocked-pattern"
  | "blocked-domain"
  | "human-coauthor"
  | "max-authors";

export interface CommitIdentity {
  name: string;
  email: string;
}

export interface CommitInput {
  sha: string;
  message: string;
  authorName: string;
  authorEmail: string;
}

export interface CoAuthor extends CommitIdentity {
  line: string;
}

export interface GommageRules {
  noAiCoauthor: boolean;
  maxAuthors: number | null;
  allowHumanCoauthors: boolean;
  blockedPatterns: string[];
  blockedDomains: string[];
  allowedPatterns: string[];
}

export interface GommageScope {
  range?: string;
}

export interface GommageConfig {
  version: 1;
  rules: GommageRules;
  scope: GommageScope;
}

export interface ConfigLoadResult {
  config: GommageConfig;
  path: string | null;
}

export interface Violation {
  code: ViolationCode;
  message: string;
  line: string;
}

export interface CommitCheckResult {
  commit: CommitInput;
  coAuthors: CoAuthor[];
  violations: Violation[];
}

export interface CheckResult {
  config: GommageConfig;
  commits: CommitCheckResult[];
  violationCount: number;
}

export interface LoadConfigOptions {
  cwd?: string;
  configPath?: string;
}

export interface CheckGitRangeOptions extends LoadConfigOptions {
  range?: string;
}

export interface CheckMessageFileOptions extends LoadConfigOptions {
  messageFile: string;
}

const CONFIG_FILE_NAME = ".gommage.yml";

const DEFAULT_CONFIG: GommageConfig = {
  version: 1,
  rules: {
    noAiCoauthor: true,
    maxAuthors: null,
    allowHumanCoauthors: true,
    blockedPatterns: [],
    blockedDomains: [],
    allowedPatterns: [],
  },
  scope: {},
};

const AI_NAME_PATTERNS = [
  /\bclaude(?:\s+code)?\b/i,
  /\bcodex\b/i,
  /\bgithub\s+copilot\b/i,
  /\bcopilot\b/i,
  /\bcursor\b/i,
  /\bdevin\b/i,
  /\bopencode\b/i,
  /\bcodeium\b/i,
  /\btabnine\b/i,
  /\bcline\b/i,
  /\bcontinue\b/i,
  /\baider\b/i,
  /\bwindsurf\b/i,
  /\baugment\b/i,
  /\bcody\b/i,
];

const AI_EMAIL_PATTERNS = [
  /anthropic/i,
  /copilot/i,
  /cursor/i,
  /devin/i,
  /opencode/i,
  /codeium/i,
  /tabnine/i,
  /openai/i,
  /cline/i,
  /continue/i,
  /aider/i,
  /windsurf/i,
  /augment/i,
  /sourcegraph/i,
];

const DEFAULT_BADGE_PATTERNS = [
  /(?:^|\s)🤖\s*generated with\b/i,
  /\bgenerated with \[(?:claude(?:\s+code)?|cursor|codex|github copilot|copilot|devin|opencode|codeium|tabnine|cline|continue|aider|windsurf|augment)\]/i,
  /\bgenerated with (?:claude(?:\s+code)?|cursor|codex|github copilot|copilot|devin|opencode|codeium|tabnine|cline|continue|aider|windsurf|augment)\b/i,
  /\bgenerated by (?:github\s+)?copilot\b/i,
];

export function getDefaultConfig(): GommageConfig {
  return structuredClone(DEFAULT_CONFIG);
}

export function loadConfig(options: LoadConfigOptions = {}): ConfigLoadResult {
  const cwd = resolve(options.cwd ?? process.cwd());
  const configPath = options.configPath ? resolve(cwd, options.configPath) : findConfigPath(cwd);

  if (!configPath) {
    return {
      config: getDefaultConfig(),
      path: null,
    };
  }

  const raw = readFileSync(configPath, "utf8");
  const parsed = parse(raw) as Record<string, unknown> | null;

  return {
    config: mergeConfig(parsed),
    path: configPath,
  };
}

export function checkCommitMessage(
  commit: CommitInput,
  config: GommageConfig = getDefaultConfig(),
): CommitCheckResult {
  const coAuthors = extractCoAuthors(commit.message);
  const allowMatchers = config.rules.allowedPatterns.map(toPattern);
  const violations: Violation[] = [];

  for (const coAuthor of coAuthors) {
    if (config.rules.noAiCoauthor && isAiIdentity(coAuthor)) {
      pushViolation(violations, allowMatchers, {
        code: "ai-coauthor",
        message: `AI co-authorship detected: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }

    if (!config.rules.allowHumanCoauthors && !isAiIdentity(coAuthor)) {
      pushViolation(violations, allowMatchers, {
        code: "human-coauthor",
        message: `Human co-author not allowed by policy: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }

    if (matchesBlockedDomain(coAuthor.email, config.rules.blockedDomains)) {
      pushViolation(violations, allowMatchers, {
        code: "blocked-domain",
        message: `Blocked email domain detected: "${coAuthor.line}"`,
        line: coAuthor.line,
      });
    }
  }

  if (matchesBlockedDomain(commit.authorEmail, config.rules.blockedDomains)) {
    const line = `Author: ${commit.authorName} <${commit.authorEmail}>`;
    pushViolation(violations, allowMatchers, {
      code: "blocked-domain",
      message: `Blocked email domain detected: "${line}"`,
      line,
    });
  }

  const lines = splitMessageLines(commit.message);

  for (const line of lines) {
    let matchedDefaultBadge = false;

    for (const pattern of DEFAULT_BADGE_PATTERNS) {
      if (pattern.test(line)) {
        matchedDefaultBadge = true;
        pushViolation(violations, allowMatchers, {
          code: "ai-badge",
          message: `AI generation badge found: "${line}"`,
          line,
        });
      }
    }

    if (matchedDefaultBadge) {
      continue;
    }

    for (const entry of config.rules.blockedPatterns) {
      const pattern = toPattern(entry);
      if (pattern.test(line)) {
        pushViolation(violations, allowMatchers, {
          code: "blocked-pattern",
          message: `Blocked pattern matched: "${line}"`,
          line,
        });
      }
    }
  }

  const maxAuthors = config.rules.maxAuthors;
  if (maxAuthors !== null) {
    const authorCount = 1 + coAuthors.length;
    if (authorCount > maxAuthors) {
      const line = `authors=${authorCount} max=${maxAuthors}`;
      pushViolation(violations, allowMatchers, {
        code: "max-authors",
        message: `Commit exceeds max authors policy (${authorCount}/${maxAuthors}).`,
        line,
      });
    }
  }

  return {
    commit,
    coAuthors,
    violations: dedupeViolations(violations),
  };
}

export function checkCommits(
  commits: CommitInput[],
  config: GommageConfig = getDefaultConfig(),
): CheckResult {
  const results = commits.map((commit) => checkCommitMessage(commit, config));

  return {
    config,
    commits: results,
    violationCount: results.reduce((count, result) => count + result.violations.length, 0),
  };
}

export function checkGitRange(options: CheckGitRangeOptions = {}): CheckResult {
  const { config } = loadConfig(options);
  const commits = readCommitsFromGit({
    cwd: options.cwd,
    range: options.range ?? config.scope.range ?? "HEAD",
  });

  return checkCommits(commits, config);
}

export function checkMessageFile(options: CheckMessageFileOptions): CheckResult {
  const { config } = loadConfig(options);
  const message = readFileSync(resolve(options.cwd ?? process.cwd(), options.messageFile), "utf8");
  const commit: CommitInput = {
    sha: "COMMIT_MSG",
    message,
    authorName: "",
    authorEmail: "",
  };

  return checkCommits([commit], config);
}

export function readCommitsFromGit(options: { cwd?: string; range: string }): CommitInput[] {
  const cwd = resolve(options.cwd ?? process.cwd());
  const output = execFileSync(
    "git",
    ["log", "--format=%H%x00%an%x00%ae%x00%B%x00%x1e", options.range],
    {
      cwd,
      encoding: "utf8",
    },
  );

  return output
    .split("\x1e")
    .map((chunk: string) => chunk.trim())
    .filter(Boolean)
    .map((chunk: string) => {
      const [sha, authorName, authorEmail, message] = chunk.split("\x00");

      return {
        sha,
        authorName,
        authorEmail,
        message: (message ?? "").trimEnd(),
      };
    });
}

export function formatCheckResult(result: CheckResult): string {
  if (result.violationCount === 0) {
    if (result.commits.length === 0) {
      return "Gommage checked 0 commits and found no violations.";
    }

    return `Gommage checked ${result.commits.length} commit(s) and found no violations.`;
  }

  const blocks = result.commits
    .filter((commit) => commit.violations.length > 0)
    .map((commit) => {
      const commitLabel =
        commit.commit.sha === "COMMIT_MSG"
          ? "commit message"
          : `commit ${commit.commit.sha.slice(0, 7)}`;
      const header = `Gommage found ${commit.violations.length} violation(s) in ${commitLabel}:`;
      const lines = commit.violations.map(
        (violation) => `  x [${violation.code}] ${violation.message}`,
      );

      return [header, "", ...lines].join("\n");
    });

  blocks.push(
    "",
    "Hint: Configure your AI tool to disable co-authorship, or update .gommage.yml to allow it.",
  );

  return blocks.join("\n");
}

export function hasViolations(result: CheckResult): boolean {
  return result.violationCount > 0;
}

function findConfigPath(startDir: string): string | null {
  let current = startDir;

  while (true) {
    const candidate = resolve(current, CONFIG_FILE_NAME);
    if (existsSync(candidate)) {
      return candidate;
    }

    const parent = dirname(current);
    if (parent === current) {
      return null;
    }

    current = parent;
  }
}

function mergeConfig(parsed: Record<string, unknown> | null): GommageConfig {
  if (!parsed) {
    return getDefaultConfig();
  }

  const version = parsed.version;
  if (version !== undefined && version !== 1) {
    throw new Error(`Unsupported .gommage.yml version: ${String(version)}`);
  }

  const rules = asObject(parsed.rules);
  const scope = asObject(parsed.scope);
  const defaults = getDefaultConfig();

  return {
    version: 1,
    rules: {
      noAiCoauthor: asBoolean(rules["no-ai-coauthor"], defaults.rules.noAiCoauthor),
      maxAuthors: asNullableNumber(rules["max-authors"], defaults.rules.maxAuthors),
      allowHumanCoauthors: asBoolean(
        rules["allow-human-coauthors"],
        defaults.rules.allowHumanCoauthors,
      ),
      blockedPatterns: asStringArray(rules["blocked-patterns"], defaults.rules.blockedPatterns),
      blockedDomains: asStringArray(rules["blocked-domains"], defaults.rules.blockedDomains),
      allowedPatterns: asStringArray(rules["allowed-patterns"], defaults.rules.allowedPatterns),
    },
    scope: {
      range: asOptionalString(scope.range),
    },
  };
}

function extractCoAuthors(message: string): CoAuthor[] {
  return splitMessageLines(message)
    .map((line) => {
      const match = /^Co-authored-by:\s*(.+?)\s*<([^>]+)>\s*$/i.exec(line);
      if (!match) {
        return null;
      }

      return {
        line,
        name: match[1].trim(),
        email: match[2].trim(),
      };
    })
    .filter((value): value is CoAuthor => value !== null);
}

function isAiIdentity(identity: CommitIdentity): boolean {
  return (
    AI_NAME_PATTERNS.some((pattern) => pattern.test(identity.name)) ||
    AI_EMAIL_PATTERNS.some((pattern) => pattern.test(identity.email))
  );
}

function matchesBlockedDomain(email: string, blockedDomains: string[]): boolean {
  if (!email) {
    return false;
  }

  const normalizedEmail = email.toLowerCase();
  const atIndex = normalizedEmail.lastIndexOf("@");
  const domain = atIndex === -1 ? normalizedEmail : normalizedEmail.slice(atIndex + 1);

  return blockedDomains.some((entry) => {
    const normalizedEntry = entry.toLowerCase();
    if (!normalizedEntry) {
      return false;
    }

    if (normalizedEntry.includes("@")) {
      return normalizedEmail === normalizedEntry;
    }

    return domain === normalizedEntry || domain.endsWith(`.${normalizedEntry}`);
  });
}

function pushViolation(
  violations: Violation[],
  allowMatchers: RegExp[],
  violation: Violation,
): void {
  if (allowMatchers.some((matcher) => matcher.test(violation.line))) {
    return;
  }

  violations.push(violation);
}

function dedupeViolations(violations: Violation[]): Violation[] {
  const seen = new Set<string>();

  return violations.filter((violation) => {
    const key = `${violation.code}:${violation.line}`;
    if (seen.has(key)) {
      return false;
    }

    seen.add(key);
    return true;
  });
}

function toPattern(value: string): RegExp {
  const raw = value.trim();
  const regexMatch = /^\/(.+)\/([dgimsuvy]*)$/.exec(raw);
  if (regexMatch) {
    return new RegExp(regexMatch[1], regexMatch[2]);
  }

  return new RegExp(escapeRegExp(raw), "i");
}

function splitMessageLines(message: string): string[] {
  return message
    .split(/\r?\n/u)
    .map((line) => line.trim())
    .filter(Boolean);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function asObject(value: unknown): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return {};
  }

  return value as Record<string, unknown>;
}

function asBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === "boolean" ? value : fallback;
}

function asNullableNumber(value: unknown, fallback: number | null): number | null {
  if (value === null) {
    return null;
  }

  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

function asStringArray(value: unknown, fallback: string[]): string[] {
  if (!Array.isArray(value)) {
    return [...fallback];
  }

  return value.filter((entry): entry is string => typeof entry === "string");
}

function asOptionalString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}
